services:
  server:
    build:
      context: .
      target: airhouse-app
    container_name: airhouse-app
    hostname: airhouse-app
    ports:
      - 8000:8000
    entrypoint: ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
  test:
    build:
      context: .
      target: airhouse-test
    container_name: airhouse-test
  migrate:
    build:
      context: .
      target: airhouse-migrate
    container_name: airhouse-migrate
    entrypoint: ./backend/manage.py migrate
    volumes:
      - .:/app/
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
